---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: podinfo
  name: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:3.1.5
        ports:
        - containerPort: 9898
